In [2]:
import pandas as pd
import datetime

In [3]:
# 2023년 대여소별 자전거 대여건수 데이터와 2023년 날씨+미세먼지 데이터 불러오기
station_rental_2023 = pd.read_csv('2023년 대여소별 공공자전거 대여건수(시간대별).csv')
weather_dust_2023 = pd.read_csv('[결측치 제거]2023년 날씨+미세먼지정보.csv', encoding='cp949')

In [4]:
station_rental_2023

              대여일자  대여시간  대여소번호         대여소명  이용건수  평일구분
0       2023-01-01     0    574     아차산역4번출구     0  평일 외
1       2023-01-01     1    574     아차산역4번출구     1  평일 외
2       2023-01-01     2    574     아차산역4번출구     0  평일 외
3       2023-01-01     3    574     아차산역4번출구     0  평일 외
4       2023-01-01     4    574     아차산역4번출구     0  평일 외
...            ...   ...    ...          ...   ...   ...
262795  2023-12-31    19   1175  대한항공 인력개발센터     0  평일 외
262796  2023-12-31    20   1175  대한항공 인력개발센터     1  평일 외
262797  2023-12-31    21   1175  대한항공 인력개발센터     2  평일 외
262798  2023-12-31    22   1175  대한항공 인력개발센터     0  평일 외
262799  2023-12-31    23   1175  대한항공 인력개발센터     1  평일 외

[262800 rows x 6 columns]

In [5]:
# 데이터프레임 병합을 위해 열 이름 통일
weather_dust_2023.rename(columns= {'날짜' : '대여일자'}, inplace=True)
weather_dust_2023.rename(columns= {'시간대' : '대여시간'}, inplace=True)

In [6]:
weather_dust_2023[:48]

,대여일자,대여시간,기온(°C),강수량(mm),풍속(m/s),습도(%),적설(cm),1시간평균 미세먼지농도(㎍/㎥)
0,2023-01-01,0,0.9,0.0,1.4,72,0.0,63.0
1,2023-01-01,1,1.5,0.0,1.9,71,0.0,67.0
2,2023-01-01,2,1.5,0.0,1.9,72,0.0,84.0
3,2023-01-01,3,1.6,0.0,1.6,74,0.0,82.0
4,2023-01-01,4,1.5,0.0,1.4,74,0.0,87.0
5,2023-01-01,5,0.8,0.0,2.4,62,0.0,78.0
6,2023-01-01,6,-0.2,0.0,3.1,67,0.0,67.0
7,2023-01-01,7,-1.5,0.0,2.5,71,0.0,62.0
8,2023-01-01,8,-1.8,0.0,2.7,75,0.0,62.0
9,2023-01-01,9,-1.7,0.0,2.1,75,0.0,67.0
10,2023-01-01,10,-0.4,0.0,2.4,66,0.0,73.0
11,2023-01-01,11,0.4,0.0,3.6,58,0.0,71.0
12,2023-01-01,12,2.0,0.0,1.7,54,0.0,76.0
13,2023-01-01,13,3.0,0.0,2.5,45,0.0,72.0
14,2023-01-01,14,3.8,0.0,2.9,38,0.0,76.0
15,2023-01-01,15,3.1,0.0,3.1,37,0.0,56.0
16,2023-01-01,16,2.6,0.0,4.4,33,0.0,52.0
17,2023-01-01,17,1.7,0.0,3.1,29,0.0,31.0
18,2023-01-01,18,0.1,0.0,2.9,35,0.0,26.0
19,2023-01-01,19,-0.8,0.0,2.9,40,0.0,22.0
20,2023-01-01,20,-1.7,0.0,3.5,44,0.0,26.0
21,2023-01-01,21,-2.2,0.0,3.2,45,0.0,27.0
22,2023-01-01,22,-2.7,0.0,3.8,45,0.0,22.0
23,2023-01-01,23,-3.4,0.0,2.6,46,0.0,14.0
24,2023-01-02,0,-4.3,0.0,2.2,49,0.0,15.0
25,2023-01-02,1,-5.0,0.0,2.6,49,0.0,23.0
26,2023-01-02,2,-5.6,0.0,2.3,51,0.0,17.0
27,2023-01-02,3,-6.2,0.0,2.2,53,0.0,23.0
28,2023-01-02,4,-6.6,0.0,1.2,52,0.0,16.0
29,2023-01-02,5,-6.7,0.0,1.9,52,0.0,21.0
30,2023-01-02,6,-6.4,0.0,2.7,51,0.0,20.0
31,2023-01-02,7,-6.6,0.0,2.9,52,0.0,25.0
32,2023-01-02,8,-7.3,0.0,1.7,53,0.0,24.0
33,2023-01-02,9,-6.6,0.0,3.0,53,0.0,23.0
34,2023-01-02,10,-5.1,0.0,2.6,47,0.0,18.0
35,2023-01-02,11,-4.1,0.0,3.7,44,0.0,35.0
36,2023-01-02,12,-2.6,0.0,3.2,37,0.0,30.0
37,2023-01-02,13,-2.2,0.0,3.5,35,0.0,36.0
38,2023-01-02,14,-1.4,0.0,2.8,34,0.0,32.0
39,2023-01-02,15,-0.7,0.0,3.0,34,0.0,34.0
40,2023-01-02,16,-0.9,0.0,3.0,34,0.0,38.0
41,2023-01-02,17,-1.7,0.0,1.7,37,0.0,40.0
42,2023-01-02,18,-2.7,0.0,2.8,39,0.0,26.0
43,2023-01-02,19,-3.4,0.0,2.6,44,0.0,23.0
44,2023-01-02,20,-3.7,0.0,2.9,46,0.0,27.0
45,2023-01-02,21,-4.4,0.0,1.7,48,0.0,28.0
46,2023-01-02,22,-5.1,0.0,2.5,46,0.0,26.0
47,2023-01-02,23,-5.8,0.0,1.6,49,0.0,24.0

In [9]:
# 2023년 대여소별 대여건수 데이터를 기준으로 두 데이터 병합
station_weather_rental_2023 = pd.merge(station_rental_2023, weather_dust_2023, on=['대여일자', '대여시간'], how = 'left')
station_weather_rental_2023[:24]

,대여일자,대여시간,대여소번호,대여소명,이용건수,평일구분,기온(°C),강수량(mm),풍속(m/s),습도(%),적설(cm),1시간평균 미세먼지농도(㎍/㎥)
0,2023-01-01,0,574,아차산역4번출구,0,평일 외,0.9,0.0,1.4,72,0.0,63.0
1,2023-01-01,1,574,아차산역4번출구,1,평일 외,1.5,0.0,1.9,71,0.0,67.0
2,2023-01-01,2,574,아차산역4번출구,0,평일 외,1.5,0.0,1.9,72,0.0,84.0
3,2023-01-01,3,574,아차산역4번출구,0,평일 외,1.6,0.0,1.6,74,0.0,82.0
4,2023-01-01,4,574,아차산역4번출구,0,평일 외,1.5,0.0,1.4,74,0.0,87.0
5,2023-01-01,5,574,아차산역4번출구,5,평일 외,0.8,0.0,2.4,62,0.0,78.0
6,2023-01-01,6,574,아차산역4번출구,0,평일 외,-0.2,0.0,3.1,67,0.0,67.0
7,2023-01-01,7,574,아차산역4번출구,1,평일 외,-1.5,0.0,2.5,71,0.0,62.0
8,2023-01-01,8,574,아차산역4번출구,3,평일 외,-1.8,0.0,2.7,75,0.0,62.0
9,2023-01-01,9,574,아차산역4번출구,3,평일 외,-1.7,0.0,2.1,75,0.0,67.0
10,2023-01-01,10,574,아차산역4번출구,7,평일 외,-0.4,0.0,2.4,66,0.0,73.0
11,2023-01-01,11,574,아차산역4번출구,4,평일 외,0.4,0.0,3.6,58,0.0,71.0
12,2023-01-01,12,574,아차산역4번출구,4,평일 외,2.0,0.0,1.7,54,0.0,76.0
13,2023-01-01,13,574,아차산역4번출구,3,평일 외,3.0,0.0,2.5,45,0.0,72.0
14,2023-01-01,14,574,아차산역4번출구,5,평일 외,3.8,0.0,2.9,38,0.0,76.0
15,2023-01-01,15,574,아차산역4번출구,6,평일 외,3.1,0.0,3.1,37,0.0,56.0
16,2023-01-01,16,574,아차산역4번출구,7,평일 외,2.6,0.0,4.4,33,0.0,52.0
17,2023-01-01,17,574,아차산역4번출구,3,평일 외,1.7,0.0,3.1,29,0.0,31.0
18,2023-01-01,18,574,아차산역4번출구,2,평일 외,0.1,0.0,2.9,35,0.0,26.0
19,2023-01-01,19,574,아차산역4번출구,1,평일 외,-0.8,0.0,2.9,40,0.0,22.0
20,2023-01-01,20,574,아차산역4번출구,2,평일 외,-1.7,0.0,3.5,44,0.0,26.0
21,2023-01-01,21,574,아차산역4번출구,2,평일 외,-2.2,0.0,3.2,45,0.0,27.0
22,2023-01-01,22,574,아차산역4번출구,1,평일 외,-2.7,0.0,3.8,45,0.0,22.0
23,2023-01-01,23,574,아차산역4번출구,1,평일 외,-3.4,0.0,2.6,46,0.0,14.0

In [10]:
# 결측치 확인
station_weather_rental_2023.isnull().sum()

대여일자                 0
대여시간                 0
대여소번호                0
대여소명                 0
이용건수                 0
평일구분                 0
기온(°C)               0
강수량(mm)              0
풍속(m/s)              0
습도(%)                0
적설(cm)               0
1시간평균 미세먼지농도(㎍/㎥)    0
dtype: int64

In [11]:
station_weather_rental_2023.to_csv('2023년 대여소별 대여 및 기온데이터.csv', index=False, encoding='cp949')